theme: jekyll-theme-slate

title: OPC Foundation Members
name: OPC Foundation Members
locale: en-US
description: "Repositories accessible to OPC Foundation Corporate Members."

# Site Author
author:
  name: OPCFoundation
  picture: 
  email: github@opcfoundation.org
